// Generated by wxt
export {}
declare global {
  const ActionButtonRow: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ActionButtonRow']
  const ActivityIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ActivityIcon']
  const AddressCopyRow: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['AddressCopyRow']
  const BalanceCard: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['BalanceCard']
  const BalanceCardCarousel: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['BalanceCardCarousel']
  const BaseDialog: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['BaseDialog']
  const BlurContainer: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['BlurContainer']
  const ChevronDownIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ChevronDownIcon']
  const ChevronRightIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ChevronRightIcon']
  const ConfirmDialog: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ConfirmDialog']
  const ContentScriptContext: typeof import('wxt/utils/content-script-context')['ContentScriptContext']
  const ConversionRateDisplay: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ConversionRateDisplay']
  const CopyIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['CopyIcon']
  const CurrencySelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['CurrencySelector']
  const DerivedAccountCard: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['DerivedAccountCard']
  const DerivedAccountCardSkeleton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['DerivedAccountCardSkeleton']
  const ExplorerLinkButton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ExplorerLinkButton']
  const ExplorerSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ExplorerSelector']
  const EyeIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['EyeIcon']
  const EyeOffIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['EyeOffIcon']
  const GradientBackground: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['GradientBackground']
  const Icon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['Icon']
  const InputAddress: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['InputAddress']
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']
  const LanguageSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['LanguageSelector']
  const LoadingScreen: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['LoadingScreen']
  const LockIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['LockIcon']
  const MatchPattern: typeof import('wxt/utils/match-patterns')['MatchPattern']
  const MessageText: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['MessageText']
  const NetworkSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NetworkSelector']
  const NftCard: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftCard']
  const NftCardSkeleton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftCardSkeleton']
  const NftCarouselSection: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftCarouselSection']
  const NftCarouselSectionSkeleton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftCarouselSectionSkeleton']
  const NftDetailPage: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftDetailPage']
  const NftSeeAllPage: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftSeeAllPage']
  const NftSendDialog: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['NftSendDialog']
  const PasswordInput: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['PasswordInput']
  const PasswordStrengthBar: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['PasswordStrengthBar']
  const PriceChart: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['PriceChart']
  const PriceImpactBadge: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['PriceImpactBadge']
  const PrimaryButton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['PrimaryButton']
  const QRCode: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['QRCode']
  const ReceiveIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ReceiveIcon']
  const ReceiveSheet: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ReceiveSheet']
  const RefreshIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['RefreshIcon']
  const ScalesBackground: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ScalesBackground']
  const ScreenHeader: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['ScreenHeader']
  const SecondaryButton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SecondaryButton']
  const SeedWordGrid: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SeedWordGrid']
  const SeedWordInput: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SeedWordInput']
  const SendIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SendIcon']
  const SendPage: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SendPage']
  const SettingsIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SettingsIcon']
  const SettingsPageLayout: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/SettingsPageLayout')['default']
  const SettingsSheet: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SettingsSheet']
  const StepIndicator: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['StepIndicator']
  const SupportSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SupportSelector']
  const SwapAmountInput: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapAmountInput']
  const SwapDetailRow: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapDetailRow']
  const SwapInputScreen: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapInputScreen']
  const SwapReviewCard: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapReviewCard']
  const SwapReviewScreen: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapReviewScreen']
  const SwapRouteVisualization: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapRouteVisualization']
  const SwapScreen: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapScreen']
  const SwapTabSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['SwapTabSelector']
  const TextButton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TextButton']
  const TexturedBackground: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TexturedBackground']
  const TokenAbout: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenAbout']
  const TokenBadgesSection: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenBadgesSection']
  const TokenDetailPage: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenDetailPage']
  const TokenFeatures: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenFeatures']
  const TokenInfo: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenInfo']
  const TokenList: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenList']
  const TokenListItem: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenListItem']
  const TokenListSkeleton: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenListSkeleton']
  const TokenMarketData: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenMarketData']
  const TokenSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenSelector']
  const TokenSelectorModal: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TokenSelectorModal']
  const TransactionDetailModal: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TransactionDetailModal']
  const TransactionHistoryPage: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TransactionHistoryPage']
  const TransactionItem: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TransactionItem']
  const TrustedAppsSelector: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['TrustedAppsSelector']
  const WalletHeader: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['WalletHeader']
  const WalletIcon: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['WalletIcon']
  const WalletSwitcherSheet: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['WalletSwitcherSheet']
  const browser: typeof import('wxt/browser')['browser']
  const clearSessionKey: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/sessionKeyCache')['clearSessionKey']
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/utils/define-app-config')['defineAppConfig']
  const defineBackground: typeof import('wxt/utils/define-background')['defineBackground']
  const defineContentScript: typeof import('wxt/utils/define-content-script')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getSessionKey: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/sessionKeyCache')['getSessionKey']
  const hasValidSessionKey: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/sessionKeyCache')['hasValidSessionKey']
  const injectScript: typeof import('wxt/utils/inject-script')['injectScript']
  const storage: typeof import('wxt/utils/storage')['storage']
  const storeSessionKey: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/sessionKeyCache')['storeSessionKey']
  const styled: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/styled')['styled']
  const useAddressValidation: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['useAddressValidation']
  const useAppConfig: typeof import('wxt/utils/app-config')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useTokenSearch: typeof import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')['useTokenSearch']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { SettingsPageLayoutProps } from '/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/SettingsPageLayout'
  import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/SettingsPageLayout')
  // @ts-ignore
  export type { ButtonBaseProps, PrimaryButtonProps, SecondaryButtonProps, TextButtonProps, IconProps, WalletHeaderProps, BalanceCardCarouselProps, BalanceCardProps, ActionButton, ActionButtonRowProps, TokenListItemProps, TokenListProps, TokenListSkeletonProps, LoadingScreenProps, PriceChartProps, TokenInfoProps, TokenAboutProps, MarketData, TokenMarketDataProps, TokenFeaturesProps, SettingsItem, SettingsSection, SettingsSheetProps, AccountListItemProps, WalletSwitcherSheetProps, UnifiedIconProps, ScreenHeaderProps, StepIndicatorProps, GradientBackgroundProps, BlurContainerProps, BlurTint, ScalesBackgroundProps, TexturedBackgroundProps, PasswordInputProps, PasswordStrengthBarProps, QRCodeProps, BlockchainType, InputAddressProps, UseAddressValidationOptions, UseAddressValidationReturn, ValidationCallbackResult, ValidationState, NftCardProps, NftCardSkeletonProps, NftData, NftAttribute, NftDetailData, NftDetailPageProps, NftCarouselSectionProps, NftCarouselSectionSkeletonProps, NftSeeAllPageProps, TokenSelectorModalProps, TokenSelectorProps, TokenSelectorToken, UseTokenSearchResult, TokenBadgesSectionProps, TokenDetailPageProps, ReceiveSheetProps, TransactionDetailModalProps, AddressCopyRowProps, ConversionRateDisplayProps, ExplorerLinkButtonProps, PriceImpactBadgeProps, SwapRoute, SwapRouteHop, SwapRouteVisualizationProps, Transaction, TransactionFee, TransactionHistoryPageProps, TransactionItemProps, TransactionTokenAmount, TxStatus, TxType, SendPageProps, SendStep, SendToken, StepAddressAmountProps, StepConfirmationProps, StepTokenSelectProps, BridgeEstimateSimple, BridgeExchangeSimple, // Bridge types used in SwapScreen
  BridgeTokenSimple, SwapAmountInputProps, SwapChainType, SwapDetailRowProps, SwapInputScreenProps, SwapQuote, SwapReviewCardProps, SwapReviewScreenProps, SwapScreenProps, SwapStep, SwapTab, SwapTabSelectorProps, SwapToken, ActionButtonProps, ActionsProps, BaseDialogProps, BaseDialogTextFieldProps, CancelButtonProps, ContentProps, HeaderProps, ConfirmDialogProps, NftSendDialogProps, DerivedAccountCardProps, DerivedAccountCardSkeletonProps } from '/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index'
  import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/components/index')
  // @ts-ignore
  export type { SalmonMessageData, SalmonEventDetail, SalmonBackgroundMessage } from '/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/types'
  import('/Users/lucamazzarello_/Desktop/Repositories/salmon-wallet-v3/apps/extension/src/utils/types')
}
