export {
  WalletSvgIcon,
  ContentCopySvgIcon,
  SettingsSvgIcon,
  SolanaSvgIcon,
  BitcoinSvgIcon,
  EthereumSvgIcon,
  GridViewSvgIcon,
  HomeSvgIcon,
  SwapSvgIcon,
  BlinksSvgIcon,
  CallMadeSvgIcon,
  QrCodeScannerSvgIcon,
  ReceiptLongSvgIcon,
} from './SvgIcons';
