/**
 * BlinksScreen - Solana Actions / Blinks discovery
 *
 * Shows trusted hosts from the registry. The synchronous `listTrustedHosts`
 * snapshot seeds initial state (so cold-start renders something even before
 * the loader resolves), then `loadTrustedHostsRegistry` resolves and we
 * re-read so a fresh install sees the full list, not just the safety-net
 * fallback. Tapping a host navigates to the blink detail route. Source is
 * restricted to the trusted-host allowlist; no free-text URL input on this
 * screen (phishing risk gate R1).
 */

import {
  colors,
  fontFamilyNative,
  fontSize,
  letterSpacing,
  listTrustedHosts,
  loadTrustedHostsRegistry,
  ms,
  s,
  spacing,
  vs,
} from '@salmon/shared';
import { useRouter, type Href } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

import { useTabChrome } from '../../../hooks/useTabChrome';

interface HostRow {
  host: string;
}

export default function BlinksScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const { headerContentOffset, scrollBottomPadding } = useTabChrome();

  // Seed with the synchronous snapshot (may be the hardcoded safety net on
  // cold start), then refresh once the async loader resolves so the full
  // registry shows up without a manual reload.
  const [hosts, setHosts] = useState<HostRow[]>(() =>
    listTrustedHosts().map((host) => ({ host })),
  );

  useEffect(() => {
    let cancelled = false;
    void loadTrustedHostsRegistry().finally(() => {
      if (!cancelled) {
        setHosts(listTrustedHosts().map((host) => ({ host })));
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const handlePressHost = (host: string) => {
    // Cast to Href: typed-routes table is regenerated by `expo start`; until
    // then the static `/blink-detail` literal isn't in the union yet.
    router.push({ pathname: '/blink-detail', params: { host } } as unknown as Href);
  };

  return (
    <View style={styles.container}>
      <Text
        style={[styles.pageTitle, { marginTop: headerContentOffset + vs(8) }]}
      >
        {t('blinks.title')}
      </Text>

      {hosts.length === 0 ? (
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>{t('blinks.empty_state')}</Text>
        </View>
      ) : (
        <FlatList
          testID="blinks-tab-list"
          data={hosts}
          keyExtractor={(item) => item.host}
          contentContainerStyle={{ paddingBottom: scrollBottomPadding }}
          renderItem={({ item }) => (
            <TouchableOpacity
              testID={`blinks-tab-row-${item.host}`}
              accessibilityRole="button"
              accessibilityLabel={item.host}
              onPress={() => handlePressHost(item.host)}
              style={styles.row}
            >
              <Text style={styles.rowText}>{item.host}</Text>
              <Text style={styles.chevron}>›</Text>
            </TouchableOpacity>
          )}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  pageTitle: {
    fontFamily: fontFamilyNative.semiBold,
    fontSize: ms(fontSize.xl),
    fontWeight: '600',
    color: colors.text.primary,
    textAlign: 'center',
    letterSpacing: letterSpacing.wide,
    marginBottom: vs(spacing['2xl']),
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(spacing.headerPadding),
    paddingVertical: vs(spacing.lg),
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
  },
  rowText: {
    fontFamily: fontFamilyNative.medium,
    fontSize: ms(fontSize.md),
    color: colors.text.primary,
    flex: 1,
  },
  chevron: {
    fontFamily: fontFamilyNative.regular,
    fontSize: ms(fontSize.lg),
    color: colors.text.muted,
    marginLeft: s(spacing.md),
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: vs(48),
    paddingHorizontal: s(24),
  },
  emptyText: {
    fontFamily: fontFamilyNative.medium,
    fontSize: ms(fontSize.md),
    color: colors.text.muted,
    textAlign: 'center',
  },
});
